## MDP with Value Iteration

**States**

'S' : Starting State

'G' : Goal State

'X' : Danger State

'-' : Other state


**Policies**

'>' : Move East

'^' : Move North

's' : Stay

In [1]:
import numpy as np # linear algebra

In [2]:
def value_iteration(grid, p):
    
    cost = -1

    reward_goal = 10
    reward_danger = -10
    reward_other = -1

    row, col = np.shape(grid)[0], np.shape(grid)[1]
    v = np.zeros((row, col))
    pol = [['s' for _ in range(col)] for _ in range(row)]

#Value Initializaion
    for r in reversed(range(row)):
        for c in range(col):
            if grid[r][c]=='G':
                v[r][c]=reward_goal
                pol[r][c]='G'
            elif grid[r][c]=='X':
                v[r][c]=reward_danger
                pol[r][c]='X'
            elif grid[r][c]=='B':
                v[r][c]=0
                pol[r][c]='B'
            else:
                v[r][c]=reward_other
                pol[r][c]='s'

    print(v,"\n")
    
#Start Iteration
    for i in range(10000):
        vnew = np.zeros((row, col))
        for r in reversed(range(row)):
            for c in range(col):
                v0 = v[r][c]
                if grid[r][c] not in ['G','X','B']:
                    ver = v[r][c+1] if c<col-1 else v0 #Action east, outcome right
                    veu = v[r-1][c] if r>0 else v0 #Action east, outcome up
                    
                    vnl = v[r][c-1] if c>0 else v0 #Action north, outcome left
                    vnu = v[r-1][c] if r>0 else v0 #Action north, outcome up
                    
                    ve = (p*(cost+ver) + (1-p)*(cost+veu))
                    vn = (p*(cost+vnu) + (1-p)*(cost+vnl))
                    
                    vnew[r][c] = max(ve,vn)
                    if c==col-1:
                        pol[r][c] = '^' if vn>=ve else 's'
                    elif r==0:
                        pol[r][c] = '>' if ve>=vn else 's'
                    else:
                        pol[r][c] = '^' if vn>=ve else '>'
                else:
                    vnew[r][c]=v0
            
        print(vnew,"\n")
    
        equal = 0
        for r in reversed(range(row)):
            for c in range(col):
                if round(v[r][c],4)!=round(vnew[r][c],4):
                    equal = 1
        if equal == 0:
            print ("Done!!! ", i+1, " iterations\n\nPolicy:")
            for r2 in (range(row)):
                print(pol[r2])
            break
        else:
            v = vnew

In [3]:
grid = [
    ['-','-','G'],
    ['X','-','-'],
    ['-','-','-'],
    ['S','-','-'],
]

p=0.9
value_iteration(grid, p)

[[ -1.  -1.  10.]
 [-10.  -1.  -1.]
 [ -1.  -1.  -1.]
 [ -1.  -1.  -1.]] 

[[ -2.    7.9  10. ]
 [-10.   -2.    7.9]
 [ -2.9  -2.   -2. ]
 [ -2.   -2.   -2. ]] 

[[  5.91   8.79  10.  ]
 [-10.     6.9    7.8 ]
 [ -3.8   -3.     5.91]
 [ -3.09  -3.    -3.  ]] 

[[  7.502   8.879  10.   ]
 [-10.      6.899   8.69 ]
 [ -4.7     5.009   5.72 ]
 [ -4.08   -4.      4.019]] 

[[  7.7413   8.8879  10.    ]
 [-10.       7.7089   8.6899]
 [  2.5081   4.8379   7.3219]
 [ -5.07     3.118    3.748 ]] 

[[  7.77324   8.88879  10.     ]
 [-10.        7.7097    8.77089]
 [  2.35411   6.3606    7.3047 ]
 [  2.05701   2.85699   5.90151]] 

[[  7.777235   8.888879  10.      ]
 [-10.         7.78268    8.77097 ]
 [  3.72454    6.3452     7.529861]
 [  1.806702   4.947419   5.859929]] 

[[  7.7777146   8.8888879  10.       ]
 [-10.          7.7827609   8.778268 ]
 [  3.71068     6.5551429   7.528393 ]
 [  3.8251311   4.9084561   6.2716168]] 

[[  7.77777057   8.88888879  10.        ]
 [-10.           7.789

In [4]:
p=0.8
value_iteration(grid, p)

[[ -1.  -1.  10.]
 [-10.  -1.  -1.]
 [ -1.  -1.  -1.]
 [ -1.  -1.  -1.]] 

[[ -2.    6.8  10. ]
 [-10.   -2.    6.8]
 [ -3.8  -2.   -2. ]
 [ -2.   -2.   -2. ]] 

[[  4.04   8.36  10.  ]
 [-10.     5.8    6.6 ]
 [ -4.6   -3.     4.04]
 [ -3.36  -3.    -3.  ]] 

[[  6.496   8.672  10.   ]
 [-10.      5.952   8.16 ]
 [ -5.4     3.392   3.68 ]
 [ -4.32   -4.      1.632]] 

[[  7.2368   8.7344  10.    ]
 [-10.       7.2624   8.1904]
 [ -0.2864   3.1344   6.2064]
 [ -5.28     0.984    1.144 ]] 

[[  7.43488   8.74688  10.     ]
 [-10.        7.2992    8.45248]
 [ -0.49248   5.4176    6.1792 ]
 [ -0.27008   0.54208   4.16192]] 

[[  7.48448    8.749376  10.      ]
 [-10.         7.51136    8.45984 ]
 [  1.33408    5.4032     6.845504]
 [ -0.664832   3.413056   4.051776]] 

[[  7.4963968   8.7498752  10.       ]
 [-10.          7.5177472   8.502272 ]
 [  1.32256     5.9786752   6.848512 ]
 [  1.9972608   3.3220608   5.1590144]] 

[[  7.49917952   8.74997504  10.        ]
 [-10.           7.551

In [5]:
p=0.99
value_iteration(grid, p)

[[ -1.  -1.  10.]
 [-10.  -1.  -1.]
 [ -1.  -1.  -1.]
 [ -1.  -1.  -1.]] 

[[ -2.     8.89  10.  ]
 [-10.    -2.     8.89]
 [ -2.09  -2.    -2.  ]
 [ -2.    -2.    -2.  ]] 

[[  7.7811   8.9889  10.    ]
 [-10.       7.89     8.88  ]
 [ -3.08    -3.       7.7811]
 [ -3.0009  -3.      -3.    ]] 

[[  7.976822   8.989889  10.      ]
 [-10.         7.881089   8.9789  ]
 [ -4.07       6.782189   7.7612  ]
 [ -4.0008    -4.         6.673289]] 

[[  7.97975833   8.98989889  10.        ]
 [-10.           7.97900989   8.97881089]
 [  5.61436711   6.76239889   7.95693289]
 [ -5.0007       5.674378     6.643588  ]] 

[[  7.97979748   8.98989899  10.        ]
 [-10.           7.97892177   8.9797901 ]
 [  5.5947749    6.95715366   7.95664677]
 [  4.67377789   5.64477611   6.93410734]] 

[[  7.97979797   8.98989899  10.        ]
 [-10.           7.97989119   8.97978922]
 [  5.78758212   6.95686952   7.95956373]
 [  4.6442761    5.9343378    6.93352806]] 

[[  7.97979798   8.98989899  10.        ]
 